import Footer from '@/components/footer/footer';
import Navbar from '@/components/navbar/Navbar';
import { cn } from 'cn';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import './footer.css';
import './globals.css';
import './header.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'RootSource (Development)',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang='en'
      className={cn(
        geistSans.variable,
        geistMono.variable,
        'h-full antialiased'
      )}
    >
      <body className='page-body'>
        <div className='app-shell'>
          <header className='site-header'>
            <div className='page-container'>
              <Navbar />
            </div>
          </header>

          <main className='page-container main-content'>{children}</main>

          <Footer />
        </div>
      </body>
    </html>
  );
}
